"""
Pipeline: pokemonpricetracker.com data → eBay image analysis → email

Steps:
  1. Load .tmp/ppt_cards.csv (generated by running scrape_ppt.py locally — site
     IP-blocks cloud runners, so this file must be created on your local machine)
  2. Filter: PSA 9/10 price must exceed raw by at least grading_fee + $5
  3. analyze_card_images: find cheapest eBay raw listing per card, analyze photos
     with Claude Vision — top 15 by expected_profit (this is the primary quality filter)
  4. Email final shortlist: card, raw price, PSA 9/10, profit %, gem rate, predicted grade

To generate fresh PPT data (run locally, not in Codespace):
    python execution/scrape_ppt.py

Usage:
    python execution/run_analysis.py
    python execution/run_analysis.py --skip-images     # skip eBay image analysis step
    python execution/run_analysis.py --skip-sheets --skip-email
"""

import argparse
import os
import smtplib
import sys
import urllib.parse
from datetime import date
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

import pandas as pd
from dotenv import load_dotenv

sys.path.insert(0, str(Path(__file__).parent))

import analyze_card_images as images_mod

PPT_PATH = ".tmp/ppt_cards.csv"
OUTPUT_PATH = ".tmp/flip_opportunities.csv"
SHORTLIST_PATH = ".tmp/final_shortlist.csv"

IMAGE_ANALYSIS_CAP = 15  # max cards sent to Claude Vision per run


# ── Google Sheets ───────────────────────────────────────────────────────────────

def push_to_google_sheets(df: pd.DataFrame, spreadsheet_id: str, tab_name: str) -> str | None:
    try:
        import gspread
        from google.oauth2.credentials import Credentials
        from google.auth.transport.requests import Request

        scopes = ["https://www.googleapis.com/auth/spreadsheets"]
        creds = None
        if Path("token.json").exists():
            creds = Credentials.from_authorized_user_file("token.json", scopes)
        if not creds or not creds.valid:
            if creds and creds.expired and creds.refresh_token:
                creds.refresh(Request())
            else:
                print("  Google credentials not set up — skipping Sheets output.")
                return None

        gc = gspread.authorize(creds)
        sh = gc.open_by_key(spreadsheet_id)
        try:
            ws = sh.worksheet(tab_name)
            ws.clear()
        except gspread.WorksheetNotFound:
            ws = sh.add_worksheet(title=tab_name, rows=500, cols=20)

        df_out = df.copy().fillna("")
        ws.update([df_out.columns.tolist()] + df_out.values.tolist())
        url = f"https://docs.google.com/spreadsheets/d/{spreadsheet_id}"
        print(f"  Pushed {len(df)} rows to Google Sheets: {url}")
        return url

    except ImportError:
        print("  gspread not installed — skipping.")
        return None
    except Exception as e:
        print(f"  Google Sheets error: {e}")
        return None


# ── Email ────────────────────────────────────────────────────────────────────

def _fmt_price(val) -> str:
    try:
        f = float(val)
        return "—" if f != f else f"${f:.2f}"  # f != f is True only for NaN
    except (TypeError, ValueError):
        return "—"


def _fmt_pct(val) -> str:
    try:
        f = float(val)
        return "—" if f != f else f"{f * 100:.1f}%"
    except (TypeError, ValueError):
        return "—"


def format_email_body(opportunities: pd.DataFrame, today: str, has_image_analysis: bool = False) -> tuple[str, str]:
    """Return (html_body, plain_body)."""
    subject_line = f"Pokemon Card Flip Opportunities — {today}"
    if has_image_analysis:
        count_summary = (f"<strong>{len(opportunities)}</strong> cards passed all filters "
                         f"including eBay photo analysis (Claude Vision)")
    else:
        count_summary = f"<strong>{len(opportunities)}</strong> cards with a positive grading spread"

    if opportunities.empty:
        html = f"""<html><body style="font-family:sans-serif;color:#222;">
<h2>{subject_line}</h2>
<p>No cards passed image analysis today.</p>
</body></html>"""
        plain = f"{subject_line}\n\nNo cards passed image analysis today."
        return html, plain

    # Only include cards with a specific listing URL — skip generic "Find on eBay" cards
    if "ebay_listing_url" in opportunities.columns:
        opportunities = opportunities[
            opportunities["ebay_listing_url"].notna() &
            (opportunities["ebay_listing_url"] != "")
        ].copy()

    # Final safety net: never show the same card twice regardless of card_number variant
    opportunities = opportunities.drop_duplicates(subset=["card_name", "set_name"], keep="first").copy()

    rows_html = []
    rows_plain = []
    for rank, (_, row) in enumerate(opportunities.iterrows(), 1):
        name = row.get("card_name", "?")
        set_name = row.get("set_name", "?")
        _ebay_price = row.get("ebay_price")
        _raw_price = row.get("raw_price")
        buy_price_val = _ebay_price if pd.notna(_ebay_price) else _raw_price
        raw = _fmt_price(buy_price_val)
        psa9 = _fmt_price(row.get("psa9_price"))
        psa10 = _fmt_price(row.get("psa10_price"))
        is_breakeven = row.get("track") == "breakeven"
        gem_val = row.get("gem_rate")
        total = row.get("total_graded")
        psa9_count = row.get("psa9_count")
        psa10_count = row.get("psa10_count")
        if pd.notna(gem_val) and gem_val == gem_val:
            pct = f"{gem_val * 100:.1f}%"
            pop_src = row.get("pop_source") or ""
            if pd.notna(psa9_count) and pd.notna(psa10_count) and pd.notna(total):
                src_label = " eBay proxy" if pop_src == "ebay_proxy" else ""
                gem = f"{pct} ({int(psa9_count + psa10_count):,} / {int(total):,}{src_label})"
            else:
                gem = pct
        elif is_breakeven:
            be = row.get("breakeven_gem_rate")
            gem = f"BE ≤ {_fmt_pct(be)}" if pd.notna(be) and be == be else "No data"
        else:
            gem = "—"
        roi_val = row.get("roi")
        if pd.notna(roi_val) and roi_val == roi_val:
            roi = _fmt_pct(roi_val)
        elif is_breakeven:
            roi = "breakeven play"
        else:
            roi = "—"
        url = row.get("source_url") or ""
        _ebay_raw = row.get("ebay_listing_url")
        ebay_listing_url = str(_ebay_raw) if pd.notna(_ebay_raw) and _ebay_raw else ""

        ebay_search_url = (
            "https://www.ebay.com/sch/i.html?"
            + urllib.parse.urlencode({
                "_nkw": f"{name} {set_name} pokemon",
                "_sop": "15",
            })
        )
        buy_url = ebay_listing_url or ebay_search_url

        pred_grade = row.get("predicted_grade")
        psa9p = row.get("psa9_or_better_probability")
        _notes_raw = row.get("notes")
        notes = str(_notes_raw) if pd.notna(_notes_raw) and _notes_raw else ""

        card_link = f'<a href="{url}" style="color:#1a73e8;text-decoration:none;">{name}</a>' if url else name
        if ebay_listing_url:
            ebay_link = (
                f' <a href="{ebay_listing_url}" style="font-size:11px;color:#e67e00;font-weight:600;">[Buy this listing]</a>'
                f' <a href="{ebay_search_url}" style="font-size:11px;color:#6b7280;">[Search if sold]</a>'
            )
        else:
            ebay_link = f' <a href="{ebay_search_url}" style="font-size:11px;color:#e67e00;font-weight:600;">[Find on eBay]</a>'

        image_plain = ""
        notes_html = ""
        if has_image_analysis and notes:
            image_plain = f"\n  Note: {notes}"
            notes_html = f"<br><span style='font-size:11px;color:#9ca3af;font-style:italic;'>{notes}</span>"

        rows_html.append(f"""<tr style="border-bottom:1px solid #e5e7eb;">
  <td style="padding:10px 14px;font-weight:500;">{rank}. {card_link}{ebay_link}<br>
    <span style="font-size:12px;color:#6b7280;">{set_name}</span>
    {notes_html}
  </td>
  <td style="padding:10px 14px;text-align:right;">{raw}</td>
  <td style="padding:10px 14px;text-align:right;">{psa9}</td>
  <td style="padding:10px 14px;text-align:right;font-weight:600;color:#15803d;">{psa10}</td>
  <td style="padding:10px 14px;text-align:right;font-weight:700;color:#15803d;">{gem}</td>
</tr>""")

        link_text = f"\n  Buy on eBay: {buy_url}" + (f"\n  PriceCharting: {url}" if url else "")
        rows_plain.append(
            f"#{rank} {name} | {set_name}\n"
            f"  Raw: {raw}  PSA9: {psa9}  PSA10: {psa10}  Gem Rate: {gem}"
            f"{image_plain}{link_text}"
        )

    image_footer = ""
    if has_image_analysis:
        image_footer = " Cards shown passed eBay photo analysis (Claude Vision)."

    table_rows = "\n".join(rows_html)
    html = f"""<html><body style="font-family:sans-serif;color:#222;max-width:960px;margin:0 auto;">
<h2 style="color:#1e293b;">{subject_line}</h2>
<p style="color:#64748b;">{count_summary}</p>
<table style="width:100%;border-collapse:collapse;font-size:14px;">
  <thead>
    <tr style="background:#f1f5f9;text-align:left;">
      <th style="padding:10px 14px;">Card</th>
      <th style="padding:10px 14px;text-align:right;">{"Buy Price (eBay)" if has_image_analysis else "Raw (Ungraded)"}</th>
      <th style="padding:10px 14px;text-align:right;">PSA 9</th>
      <th style="padding:10px 14px;text-align:right;">PSA 10</th>
      <th style="padding:10px 14px;text-align:right;">Gem Rate (gem / total)</th>
    </tr>
  </thead>
  <tbody>
{table_rows}
  </tbody>
</table>
<p style="font-size:12px;color:#94a3b8;margin-top:24px;">
  Gem Rate = % of all PSA submissions that came back 9 or 10 (gem count / total graded). BE ≤ X% = breakeven if at least X% grade gem.{image_footer}
</p>
</body></html>"""

    plain = f"{subject_line}\n{len(opportunities)} cards\n\n"
    plain += "\n\n".join(rows_plain)
    return html, plain


def send_email(html_body: str, plain_body: str, subject: str) -> bool:
    load_dotenv()
    smtp_host = os.environ.get("SMTP_HOST")
    smtp_port = int(os.environ.get("SMTP_PORT", 587))
    smtp_user = os.environ.get("SMTP_USER")
    smtp_pass = os.environ.get("SMTP_PASS")
    email_to = os.environ.get("EMAIL_TO")

    if not all([smtp_host, smtp_user, smtp_pass, email_to]):
        print("  Email not configured — skipping.")
        return False

    recipients = [a.strip() for a in email_to.split(",") if a.strip()]
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = smtp_user
    msg["To"] = ", ".join(recipients)
    msg.attach(MIMEText(plain_body, "plain"))
    msg.attach(MIMEText(html_body, "html"))

    try:
        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.ehlo()
            server.starttls()
            server.login(smtp_user, smtp_pass)
            server.sendmail(smtp_user, recipients, msg.as_string())
        print(f"  Email sent to {', '.join(recipients)}")
        return True
    except Exception as e:
        print(f"  Email failed: {e}")
        return False


# ── Main ───────────────────────────────────────────────────────────────────────

def run(
    ppt_path: str = PPT_PATH,
    skip_images: bool = False,
    skip_sheets: bool = False,
    skip_email: bool = False,
):
    load_dotenv()
    today = date.today().isoformat()
    grading_fee = float(os.environ.get("GRADING_FEE", 25.0))

    print(f"\n{'='*60}")
    print(f"Pokemon Flip Analysis  —  {today}")
    print(f"{'='*60}\n")

    # Step 1: Load pokemonpricetracker.com data
    if not Path(ppt_path).exists():
        print(f"[ERROR] {ppt_path} not found.")
        print("Run this on your local machine first (site blocks cloud IPs):")
        print("    python execution/scrape_ppt.py")
        print("Then copy .tmp/ppt_cards.csv here and re-run.")
        return pd.DataFrame()

    df = pd.read_csv(ppt_path)
    print(f"[1/3] Loaded {len(df)} cards from {ppt_path}")

    # Normalize ROI to decimal (PPT stores as percent, e.g. 1908 means 1908%)
    if "roi_pct" in df.columns:
        df["roi"] = df["roi_pct"] / 100
    # Compatibility: older CSVs may have gem_rate / total_population columns
    if "total_population" in df.columns:
        df["total_graded"] = df["total_population"]
    df["track"] = df.get("gem_rate", pd.Series(dtype=float)).apply(
        lambda x: "population" if pd.notna(x) else "breakeven"
    )

    # Step 2: Filter — expected_profit must exceed grading fee + margin
    # (PPT already computes expected profit accounting for grading probabilities)
    min_profit = grading_fee + 5.0
    min_raw_price = 10.0
    if "expected_profit" in df.columns and df["expected_profit"].notna().any():
        has_profit = (
            df["raw_price"].notna() &
            (df["raw_price"] >= min_raw_price) &
            df["expected_profit"].notna() &
            (df["expected_profit"] > min_profit)
        )
        df = df[has_profit].copy()
        print(f"  → {len(df)} cards with raw_price >= ${min_raw_price:.0f} and expected profit > ${min_profit:.0f}")
    elif "psa9_price" in df.columns or "psa10_price" in df.columns:
        # Legacy CSV with individual PSA prices
        min_spread = min_profit
        has_spread = (
            df["raw_price"].notna() &
            (
                (df["psa9_price"].notna() & (df["psa9_price"] - df["raw_price"] > min_spread)) |
                (df["psa10_price"].notna() & (df["psa10_price"] - df["raw_price"] > min_spread))
            )
        )
        df = df[has_spread].copy()
        print(f"  → {len(df)} cards with PSA spread > ${min_spread:.0f}")
    else:
        print("  No profit/price columns found to filter on — using all cards")
        print(f"  Columns available: {list(df.columns)}")

    if df.empty:
        print("No cards passed the spread filter.")
        _send_empty_email(today, skip_email)
        return pd.DataFrame()

    # Sort by expected profit descending
    sort_col = "expected_profit" if "expected_profit" in df.columns else "roi"
    df = df.sort_values(sort_col, ascending=False).reset_index(drop=True)

    Path(OUTPUT_PATH).parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(OUTPUT_PATH, index=False)

    n_for_vision = min(len(df), IMAGE_ANALYSIS_CAP)
    print(f"  → {n_for_vision}/{len(df)} cards → Claude Vision\n")

    # Step 3: eBay image analysis (top IMAGE_ANALYSIS_CAP by expected profit)
    final = df
    has_image_analysis = False
    if not skip_images and not df.empty:
        print(f"[2/3] Analyzing eBay listing photos (top {n_for_vision} cards, Claude Vision)...")
        shortlist = images_mod.run(input_path=OUTPUT_PATH, top_n=n_for_vision)

        analysis_csv = Path(".tmp/image_analysis.csv")
        if shortlist is not None and not shortlist.empty:
            final = shortlist
            has_image_analysis = True
            Path(SHORTLIST_PATH).parent.mkdir(parents=True, exist_ok=True)
            shortlist.to_csv(SHORTLIST_PATH, index=False)
        elif analysis_csv.exists():
            print("  No SUBMIT cards from image analysis — showing analyzed cards with eBay links.")
            final = pd.read_csv(analysis_csv)
            has_image_analysis = True
        print()
    elif skip_images:
        print("[2/3] Skipping image analysis (--skip-images)\n")

    # Google Sheets
    if not skip_sheets:
        spreadsheet_id = os.environ.get("GOOGLE_SPREADSHEET_ID")
        if spreadsheet_id:
            tab = f"Flip Analysis {today}" + (" (Vision)" if has_image_analysis else "")
            push_to_google_sheets(final, spreadsheet_id, tab)
        else:
            print("  GOOGLE_SPREADSHEET_ID not set — skipping Sheets output.")

    if "ebay_listing_url" in final.columns:
        final = final[final["ebay_listing_url"].notna() & (final["ebay_listing_url"] != "")].copy()
    final = final.drop_duplicates(subset=["card_name", "set_name"], keep="first").copy()

    # Drop cards where the actual listing price leaves no margin after grading fee
    if "ebay_price" in final.columns and has_image_analysis:
        def _still_profitable(row):
            buy = row.get("ebay_price")
            if pd.isna(buy) or buy == 0:
                return True
            psa9  = row.get("psa9_price")
            psa10 = row.get("psa10_price")
            if pd.notna(psa9)  and psa9  - buy > grading_fee:
                return True
            if pd.notna(psa10) and psa10 - buy > grading_fee:
                return True
            return False
        before = len(final)
        final = final[final.apply(_still_profitable, axis=1)].copy()
        dropped = before - len(final)
        if dropped:
            print(f"  Dropped {dropped} card(s) whose actual listing price left no margin after grading fee.")

    # Email
    if not skip_email:
        html_body, plain_body = format_email_body(final, today, has_image_analysis=has_image_analysis)
        subject = f"Your {date.today().strftime('%m/%d')} Pokenalysis: {len(final)} Opportunit{'y' if len(final) == 1 else 'ies'} Found"
        send_email(html_body, plain_body, subject)

    if final.empty:
        print("No cards met all criteria today.")
    else:
        cols = ["card_name", "set_name", "raw_price", "psa9_price", "psa10_price",
                "gem_rate", "roi", "predicted_grade", "psa9_or_better_probability"]
        print(final[[c for c in cols if c in final.columns]].to_string(index=False))

    if "ebay_listing_url" in final.columns:
        print("\n── eBay listing URLs ──")
        for _, row in final.iterrows():
            url = row.get("ebay_listing_url")
            label = url if pd.notna(url) and url else "[MISSING — will show generic search link]"
            print(f"  {row.get('card_name', '?')} | {label}")
    else:
        print("\n[WARNING] ebay_listing_url column missing from final dataframe — all links will be generic")

    out = SHORTLIST_PATH if has_image_analysis else OUTPUT_PATH
    print(f"\nFinal results saved to: {out}")
    return final


def _send_empty_email(today: str, skip_email: bool):
    if skip_email:
        return
    html = f"""<html><body style="font-family:sans-serif;color:#222;">
<h2>Pokemon Flip Analysis — {today}</h2>
<p>No cards passed the spread filter today. Check that ppt_cards.csv is fresh and that grading fee settings are reasonable.</p>
</body></html>"""
    plain = f"Pokemon Flip Analysis — {today}\n\nNo cards passed the spread filter today."
    subject = f"Your {date.today().strftime('%m/%d')} Pokenalysis: 0 Opportunities Found"
    send_email(html, plain, subject)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Pokemon card flip analysis")
    parser.add_argument("--ppt", default=PPT_PATH,
                        help="Path to ppt_cards.csv (generated by scrape_ppt.py)")
    parser.add_argument("--skip-images", action="store_true")
    parser.add_argument("--skip-sheets", action="store_true")
    parser.add_argument("--skip-email", action="store_true")
    args = parser.parse_args()

    run(
        ppt_path=args.ppt,
        skip_images=args.skip_images,
        skip_sheets=args.skip_sheets,
        skip_email=args.skip_email,
    )
